name: Testdroid User Documentation
markdown: kramdown
highlighter: rouge
#url: http://docs.testdroid.com
#baseurl: /testdroid-documentation
gems:
  - jekyll-sitemap
td_link: "[Testdroid](http://testdroid.com/)"
td_cloud: "[Testdroid Cloud](http://cloud.testdroid.com/)"
